### ISSUE TITLE
kafka客户端发送消息导致Tomcat僵死

### ISSUE THREAD

**Issue by yingqin678** [yingqin678/experience#3]
http://www.it1352.com/542429.html
出现大量日志

"http-bio-8080-exec-168" #257 daemon prio=5 os_prio=0 tid=0x00007f52ec5cc800 nid=0x501 waiting on condition [0x00007f52dcc03000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000070b8cb2a8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.kafka.clients.producer.internals.BufferPool.allocate(BufferPool.java:137)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:157)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:338)
	at com.huawei.opengw.mq.remoting.kafka.version082.KafkaProducer082.send(KafkaProducer082.java:122)
	at com.huawei.opengw.mq.rpc.MQInvoker.doInvoke(MQInvoker.java:216)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:142)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:73)
	at com.alibaba.dubbo.rpc.filter.GenericImplFilter.invoke(GenericImplFilter.java:172)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:47)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:52)
	at com.huawei.opengw.dubboex.rpc.cluster.opengw.support.MFailoverClusterInvoker.doInvoke(MFailoverClusterInvoker.java:115)
	at com.huawei.opengw.dubboex.rpc.cluster.opengw.support.AbstractMClusterInvoker.invoke(AbstractMClusterInvoker.java:344)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
	at com.sun.proxy.$Proxy46.$invoke(Unknown Source)
	at com.huawei.opengw.mq.api.MQClient.sendMessage(MQClient.java:567)
	at com.huawei.skytone.dmq.DmqClient.sendMessage(DmqClient.java:377)
	at com.huawei.skytone.dmq.DmqClient.sendMessage(DmqClient.java:349)
	at com.huawei.vsim.common.dmq.push.PushMsgService.postApkLogOnMSG(PushMsgService.java:90)
	at com.huawei.vsim.rest.v1.ifs.ReportLog.sendDMQ(ReportLog.java:278)
	at com.huawei.vsim.rest.v1.ifs.ReportLog.service(ReportLog.java:180)
	at com.huawei.vsim.rest.v1.ifs.ReportLog.service(ReportLog.java:45)
	at com.huawei.vsim.rest.v1.ClientServlet.execute(ClientServlet.java:437)
	at com.huawei.vsim.rest.v1.ClientServlet.doRequest(ClientServlet.java:354)
	at com.huawei.vsim.rest.v1.ClientServlet.doPost(ClientServlet.java:185)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:458)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.huawei.vsim.common.container.EncodingFilter.doFilter(EncodingFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:498)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	- locked <0x000000070b8cc340> (a org.apache.tomcat.util.net.SocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yingqin678** [comment]
那个问题比较难复现，我们之前也看到官方有该bug的说明，在1.3.3之后的版本优化了。
重现条件可以尝试下面的步骤：
1、建立链接
2、IPTABLE禁用9092
3、压测大消息
![image](https://user-images.githubusercontent.com/10692769/46060217-0308db00-c195-11e8-93f3-abd68c3d19f5.png)
